---
title: "EV Power - Lab 4 Project Report"
format: typst
---

# Example Solution 1

## **Part 0: libraries**


```{r}
library(readr)     
library(dplyr)      
library(stringr)   
install.packages("ggplot2")
library(ggplot2)

setwd("/Users/marcosnegrete/ev-power-marcosnegrete-ai/data")

av21_23 <- read_csv("av-energy-price-2021-2023.csv")

av21_23

```

## **Part 1:** **Defining Research Question**

Chosen Question:
1. How has each state's share of renewable electricity changed from 2021 to 2023?
2. How have average electricity prices changed from 2021–2023, and how does that relate to renewable growth?

## **Part 2: Data Preparation and Cleaning**
```{r}

names(av21_23) <- tolower(names(av21_23))  
names(av21_23) <- gsub(" ", "_", names(av21_23))  
names(av21_23) <- gsub("-", "_", names(av21_23))    
names(av21_23) <- gsub("\\(|\\)", "", names(av21_23))
```


## **Part 3: Joining / Pivoting Datasets for Analysis**

```{r}


```

## **Part 4: Mapping Visualization**

```{r}

ggplot(av21_23, aes(x = long, y = lat, group = group, fill = avg_energy_price)) +
  geom_bar(color = "darkblue") + 
  scale_fill_gradient(low = "yellow") +
  labs(title = "Average Energy Price by State (2023)",
       fill = "Avg Energy Price") 
```